### ISSUE TITLE
Use `aes` crate?

### ISSUE THREAD

**Issue by tarcieri** [Argyle-Software/kyber#100]
I noticed this crate vendors a [portable bitsliced implementation of AES](https://github.com/Argyle-Software/kyber/blob/master/src/reference/aes256ctr.rs) along with an [AES-NI implementation](https://github.com/Argyle-Software/kyber/blob/master/src/avx2/aes256ctr.rs) which have been translated from the Kyber reference implementation.

Instead of that, I'd like to suggest using the [`aes` crate from @RustCrypto](https://docs.rs/aes/). It includes a portable "[fixsliced](https://eprint.iacr.org/2020/1123.pdf)" implementation of AES, AES-NI support, and also support for the ARMv8 Cryptography Extensions. Additionally it implements runtime CPU feature detection on both x86 and ARM to determine if the hardware implementations are available, falling back to the portable implementations if not.

**Comment by mberry** [comment]
The `90s-fixslice` feature [uses the aes crate](https://github.com/Argyle-Software/kyber/blob/476e22c1a1ed579f3030e1ae46077036dc384d7f/src/symmetric.rs#L105-L121)

That said, all the vendored AES code should be carved out of this repo, the fixslice feature was added on rather than a replacement for codebase stability/dependency reasons. Feature deprecation isn't really there yet in rust.

Somewhat offtopic: enforcing cargo fmt standard style really did a number on all the instantiation in aes256ctr.rs

**Comment by tarcieri** [comment]
Oh, my bad, I'm not sure how I missed that
